dist: trusty
language: php

branches:
  only:
  - master
  - "/^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+.*$/"

matrix:
  fast_finish: true
  include:
  - php: 7.2
  - php: 7.1
  - php: 7.0.11
  - php: 5.6
    env: INSTALL_COMMAND='update --prefer-lowest'
  - php: 5.4
    env: INSTALL_COMMAND='update --prefer-lowest'

sudo: false

cache:
  directories:
  - "$HOME/.composer/cache"

install:
- composer ${INSTALL_COMMAND:-install}

script:
- composer test

after_success:
- travis_retry php vendor/bin/php-coveralls -v
